### PR TITLE
Update page title with CommIT Group name

### PR DESCRIPTION
**Pull request by car2t**
We should use our group name and also our own favicon in our projects.

### CODE REVIEW

**Comment by WitchDevelops** [comment]
sure! I'm up for using our own favicon. Do we want one for all the projects or a different one for each? Any ideas?

We need to get our code formatting together 0 you changed one thing here, but formatting ALSO got changed practuically everywhere...

**Review by WitchDevelops — APPROVED** [review]
- [x] good change, I approve
- [ ] formatting, nooo....

**Comment by car2t** [comment]
> sure! I'm up for using our own favicon. Do we want one for all the projects or a different one for each? Any ideas?
> 
> We need to get our code formatting together 0 you changed one thing here, but formatting ALSO got changed practuically everywhere...

Hi Domi 
Yep, I agree. 
I have not did anything special in the formatting extension but it changes stuff. Maybe I need to get rid of it while working on this.
It would be easier have our own set up for that. 
Our FAVICON could be a Blue Rocket, as in our group, or a cat light violet silhouette in your honor, also everyone likes cats.

**Comment by nikkehtine** [comment]
I could add my `.prettierrc` file to the project so that we can have uniform formatting across the whole repo. Though I will need to make a little change because I really prefer those single lines rather than it spreading across multiple lines.

**Review by nikkehtine — APPROVED** [review]

**Pull request merged**
